version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ogb_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ogb-app
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - internal
    ports:
      - "127.0.0.1:3000:3000"
    command: npm start

volumes:
  postgres_data:

networks:
  internal: